# Generated by Django 5.1.4 on 2025-01-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'клиента',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Excursions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursion_name', models.CharField(max_length=100, verbose_name='Название экскурсии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('excursion_date', models.DateField(verbose_name='Дата экскурсии')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('photo_excur', models.ImageField(null=True, upload_to='photo_excur/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'экскурсию',
                'verbose_name_plural': 'Экскурсии',
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100, verbose_name='Название отеля')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактный телефон')),
                ('photo_hotel', models.ImageField(null=True, upload_to='photo_hotel/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(max_length=50, verbose_name='Тип транспорта')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании')),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер рейса')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Время отправления')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия')),
            ],
            options={
                'verbose_name': 'транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfirmaapp.customers', verbose_name='Id клиента')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Метод оплаты')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfirmaapp.bookings', verbose_name='Id бронирования')),
            ],
            options={
                'verbose_name': 'оплату',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=100, verbose_name='Название тура')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('photo_tour', models.ImageField(null=True, upload_to='photo_tour/', verbose_name='Фотография')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfirmaapp.hotels', verbose_name='Id отеля')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfirmaapp.transport', verbose_name='Id транспорта')),
            ],
            options={
                'verbose_name': 'тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfirmaapp.tours', verbose_name='Id тура'),
        ),
    ]
