# Generated by Django 5.1.4 on 2024-12-24 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name': 'бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'клиента', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='excursions',
            options={'verbose_name': 'экскурсию', 'verbose_name_plural': 'Экскурсии'},
        ),
        migrations.AlterModelOptions(
            name='hotels',
            options={'verbose_name': 'отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'оплату', 'verbose_name_plural': 'Оплаты'},
        ),
        migrations.AlterModelOptions(
            name='tours',
            options={'verbose_name': 'тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'транспорт', 'verbose_name_plural': 'Транспорт'},
        ),
        migrations.AddField(
            model_name='excursions',
            name='photo_excur',
            field=models.ImageField(null=True, upload_to='photo_excur/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='photo_hotel',
            field=models.ImageField(null=True, upload_to='photo_hotel/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='tours',
            name='photo_tour',
            field=models.ImageField(null=True, upload_to='photo_tour/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateField(verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfirmaapp.customers', verbose_name='Id клиента'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfirmaapp.tours', verbose_name='Id тура'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='registration_date',
            field=models.DateField(verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='excursion_date',
            field=models.DateField(verbose_name='Дата экскурсии'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='excursion_name',
            field=models.CharField(max_length=100, verbose_name='Название экскурсии'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_name',
            field=models.CharField(max_length=100, verbose_name='Название отеля'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfirmaapp.bookings', verbose_name='Id бронирования'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateField(verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='tour_name',
            field=models.CharField(max_length=100, verbose_name='Название тура'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='flight_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер рейса'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.CharField(max_length=50, verbose_name='Тип транспорта'),
        ),
    ]
