# Generated by Django 5.1.4 on 2025-01-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0002_tours_excursions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='excursions',
        ),
    ]
