# Generated by Django 5.1.4 on 2024-12-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0002_alter_bookings_options_alter_customers_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='tour_id',
            new_name='tour',
        ),
        migrations.RenameField(
            model_name='hotelexcursion',
            old_name='excursion_id',
            new_name='excursion',
        ),
        migrations.RenameField(
            model_name='hotelexcursion',
            old_name='hotel_id',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
