# Generated by Django 5.1.4 on 2025-01-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0003_remove_tours_excursions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='excursions',
            field=models.ManyToManyField(to='turfirmaapp.excursions'),
        ),
    ]
