# Generated by Django 5.1.6 on 2025-03-05 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0005_reviews_alter_bookings_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата отзыва'),
        ),
    ]
