# Generated by Django 5.1.6 on 2025-03-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0006_alter_reviews_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='data',
            new_name='date',
        ),
    ]
