# Generated by Django 5.1.6 on 2025-03-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0007_rename_data_reviews_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='date',
            new_name='date_review',
        ),
    ]
