# Generated by Django 5.1.6 on 2025-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0008_rename_date_reviews_date_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='number_of_views',
            field=models.IntegerField(null=True, verbose_name='Количество просмотров'),
        ),
    ]
