# Generated by Django 5.1.6 on 2025-09-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0009_tours_number_of_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='level',
            field=models.IntegerField(null=True, verbose_name='Уровень сложности'),
        ),
    ]
