# Generated by Django 5.1.6 on 2025-09-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0010_tours_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
