# Generated by Django 5.1.6 on 2025-09-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0011_reviews_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='photo',
            field=models.ImageField(blank=True, default='photo/default_avatar.png', null=True, upload_to='photo/'),
        ),
    ]
