# Generated by Django 5.1.6 on 2025-09-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0012_alter_reviews_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='photo',
            field=models.ImageField(blank=True, default='photo/default_avatar.png', null=True, upload_to='photo/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.CharField(blank=True, default='Anonymous', max_length=50, verbose_name='Пользователь'),
        ),
    ]
