# Generated by Django 5.1.6 on 2026-01-13 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0014_alter_reviews_options_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'заявку', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='excursion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turfirmaapp.excursions', verbose_name='Название экскурсии'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='star',
            field=models.IntegerField(null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turfirmaapp.tours', verbose_name='Название тура'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='number_of_views',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]
