# Generated by Django 5.1.6 on 2026-01-13 13:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfirmaapp', '0015_alter_application_options_reviews_excursion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='excursion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfirmaapp.excursions', verbose_name='Название экскурсии'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='star',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='tour',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfirmaapp.tours', verbose_name='Название тура'),
        ),
    ]
